{
 mode: inference,
 cuda: true,
 pin_memory: true,
 wandb: false,
 worker: 1,
 batch_size: 1,
 project_name: 'Pore',
 CUDA_VISIBLE_DEVICES: '0',

 model_name: 'Pore_Net',
 input_size: [1280, 1024],
 resolution: [1280, 1024],

 inference_mode: 'mask',
 threshold: 0.25,  # of range [0, 1]
 model_path: 'model_checkpoints/PoreNet.pt',

 val_x_path: 'data_examples/input_cropped/',
 val_y_path: 'data_examples/label_cropped/',

 mask_path: 'data_examples/mask_cropped/',
}