{
 ### Environment Parameters
 mode: train,
 cuda: true,
 pin_memory: true,
 wandb: true,
 worker: 8,
 log_interval: 9999,
 save_interval: 50,
 project_name: 'Pore',
 CUDA_VISIBLE_DEVICES: '1',

 ### Train Parameters
 model_name: 'Pore_Net',
 threshold: 0.4,  # the paper version is 0.4
 num_class: 2,
 criterion: 'MSE',
 input_space: 'RGB',
 crop_size: '512',
 input_size: [1280, 1024],
 resolution: [1280, 1024],
 scheduler: 'CosineAnnealingLR',
 batch_size: 16,
 epoch: 100000,
 lr: 0.0001,
 class_weight: [1.0, 1.0],

 transform_blur: true,
 transform_jitter: true,

 saved_model_directory: 'model_checkpoints',
 train_x_path: '/your/path/to/train/input',
 train_y_path: '/your/path/to/train/label',
 train_mask_path: '/your/path/to/train/roi_mask',
 val_x_path: '/your/path/to/val/input',
 val_y_path: '/your/path/to/val/label',
 val_mask_path: '/your/path/to/val/roi_mask',
}